[package]
name = "palmfft"
version = "1.3.0"
edition = "2024"
description = "Palm-sized Faster Fourier Transform"
repository = "https://github.com/H4n-uL/PalmFFT"
license = "BSD-3-Clause"

[dependencies]
libm = "0.2.15"
num-complex = { version = "0.4.6", optional = true }
